import java.util.ArrayList;

//Clase para guardar los datos usados en el programa.

public class DatosGlobales{
    public static ArrayList<PlanDeEstudio> listaPlanes= new ArrayList<>();
    public static ArrayList<Carrera> listaCarreras=new ArrayList<>();
    public static ArrayList<Alumno> listaAlumnos=new ArrayList<>();


    public static void generarPrueba(){
        boolean optativa=true;
        PlanDeEstudio planPrueba= new PlanDeEstudio();
        planPrueba.setCantidadOptativasNecesarias((byte) 2);
        planPrueba.setTipoCorrelatividad('A');
        planPrueba.setNombrePlan("Plan prueba A");
        Materia m1=new Materia();
        m1.setCuatrimestre((byte) 1);
        m1.setNombre("Expresion de algoritmos");
        byte notaPromocion= (byte) 7;
        m1.setNotaPromocion(notaPromocion);
        Materia m2=new Materia();
        m2.setNombre("Elementos de informatica");
        m2.setNotaPromocion(notaPromocion);
        m2.setCuatrimestre((byte) 1);
        Materia m3= new Materia();
        m3.setCuatrimestre((byte) 1);
        m3.setNombre("Algebra");
        m3.setNotaPromocion(notaPromocion);
        Materia m4=new Materia();
        m4.setNombre("Algoritmica y programacion I");
        m4.setCuatrimestre((byte) 2);
        m4.setNotaPromocion(notaPromocion);
        m4.addCorrelativa(m3);
        Materia m5=new Materia();
        m5.setNombre("Expresión de lógica y matematica discreta");
        m5.setCuatrimestre((byte) 2);
        m5.setNotaPromocion(notaPromocion);
        Materia m6 = new Materia();
        m6.setNombre("Analisis matematico");
        m6.setCuatrimestre((byte) 2);
        m6.setNotaPromocion(notaPromocion);
        Materia m7= new Materia();
        m7.setNombre("Sistemas y organizaciones");
        m7.setNotaPromocion(notaPromocion);
        m7.setCuatrimestre((byte) 3);
        Materia m8 = new Materia();
        m8.setNombre("Arquitectura de computadoras");
        m8.setCuatrimestre((byte) 3);
        m8.setNotaPromocion(notaPromocion);
        m8.addCorrelativa(m2);
        Materia m9 = new Materia();
        m9.setNombre("Algoritmica y programacion II");
        m9.setCuatrimestre((byte) 3);
        m9.setNotaPromocion(notaPromocion);
        m9.addCorrelativa(m4);
        m9.addCorrelativa(m5);
        Materia m10=new Materia();
        m10.setNombre("Estadistica");
        m10.addCorrelativa(m6);
        m10.addCorrelativa(m3);
        m10.setCuatrimestre((byte) 3);
        m10.setNotaPromocion(notaPromocion);
        Materia m11= new Materia();
        m11.setNombre("Base de datos I");
        m11.addCorrelativa(m9);
        m11.setCuatrimestre((byte) 4);
        m11.setNotaPromocion(notaPromocion);
        Materia m12 = new Materia();
        m12.setNombre("Programacion orientada a objetos");
        m12.addCorrelativa(m9);
        m12.setCuatrimestre((byte) 4);
        m12.setNotaPromocion((byte)11);
        Materia m13= new Materia();
        m13.setNombre("Ingenieria de Software I");
        m13.setCuatrimestre((byte) 4);
        m13.addCorrelativa(m7);
        m13.addCorrelativa(m4);
        m13.setNotaPromocion(notaPromocion);
        Materia m14 = new Materia();
        m14.setCuatrimestre((byte) 5);
        m14.setNombre("Laboratorio de Programación y Lenguajes");
        m14.setNotaPromocion(notaPromocion);
        m14.addCorrelativa(m9);
        Materia m15 = new Materia();
        m15.setNombre("Ingenieria de Software II");
        m15.addCorrelativa(m13);
        m15.addCorrelativa(m10);
        m15.setNotaPromocion(notaPromocion);
        m15.setCuatrimestre((byte)5 );
        Materia m16 =  new Materia();
        m16.setCuatrimestre((byte) 5);
        m16.setNombre("Introduccion a la concurrencia");
        m16.setNotaPromocion(notaPromocion);
        m16.addCorrelativa(m9);
        m16.addCorrelativa(m8);
        Materia m17= new Materia();
        m17.setCuatrimestre((byte) 6);
        m17.setNombre("Laboratorio de Software");
        m17.addCorrelativa(m13);
        m17.addCorrelativa(m12);
        m17.addCorrelativa(m11);
        m17.setNotaPromocion(notaPromocion);
        Materia m18 = new Materia();
        m18.setNombre("Sistemas operativos");
        m18.setCuatrimestre((byte) 6);
        m18.setNotaPromocion(notaPromocion);
        m18.addCorrelativa(m16);
        Materia mo1= new Materia();
        mo1.setNombre("Robotica");
        mo1.setCuatrimestre((byte) 3);
        mo1.setNotaPromocion(notaPromocion);
        mo1.addCorrelativa(m2);
        mo1.setOptativa(optativa);
        Materia mo2=new Materia();
        mo2.setNombre("Diseño de videojuegos");
        mo2.setCuatrimestre((byte) 5);
        mo2.addCorrelativa(m9);
        mo2.setOptativa(optativa);
        mo2.setNotaPromocion(notaPromocion);
        Materia mo3=new Materia();
        mo3.setNombre("Diseño de interfaces");
        mo3.addCorrelativa(m12);
        mo3.setCuatrimestre((byte) 6);
        mo3.setNotaPromocion(notaPromocion);
        mo3.setOptativa(optativa);
        Materia m19 = new Materia();
        m19.setNombre("Fundamentos de informatica");
        m19.setCuatrimestre((byte) 5);
        m19.setNotaPromocion(notaPromocion);
        m19.addCorrelativa(m9);
        m19.addCorrelativa(m5);
        Materia m20 = new Materia();
        m20.setNombre("Seminario de aspectos legales y profesionales");
        m20.setCuatrimestre((byte)6);
        m20.addCorrelativa(m7);
        m20.setNotaPromocion(notaPromocion);
        Materia m21= new Materia();
        m21.setNombre("Bases de datos II");
        m21.setCuatrimestre((byte)6);
        m21.addCorrelativa(m11);
        m21.setNotaPromocion(notaPromocion);
        Materia m22= new Materia();
        m22.setNombre("Redes y trasmición de datos");
        m22.setCuatrimestre((byte)7);
        m22.addCorrelativa(m18);
        m22.setNotaPromocion(notaPromocion);
        Materia m23=new Materia();
        m23.setCuatrimestre((byte)7);
        m23.setNombre("Paradigmas y lenguajes de programacion");
        m23.setNotaPromocion(notaPromocion);
        m23.addCorrelativa(m19);
        m23.addCorrelativa(m12);
        Materia m24=new Materia();
        m24.setCuatrimestre((byte)7 );
        m24.setNombre("Taller de nuevas tecnologias");
        m24.setNotaPromocion(notaPromocion);
        m24.addCorrelativa(m17);
        Materia m25=new Materia();
        m25.setCuatrimestre((byte)8);
        m25.setNombre("Sistemas distribuidos");
        m25.setNotaPromocion(notaPromocion);
        m25.addCorrelativa(m22);
        Materia m26 =new Materia();
        m26.setNombre("Ingenieria de Software III");
        m26.setCuatrimestre((byte)8);
        m26.setNotaPromocion(notaPromocion);
        m26.addCorrelativa(m15);
        Materia m27 = new Materia();
        m27.setCuatrimestre((byte)8);
        m27.setNombre("Seminario de aspectos legales y profesionales II");
        m27.setNotaPromocion(notaPromocion);
        m27.addCorrelativa(m20);
        Materia m28 = new Materia();
        m28.setNombre("Sistemas inteligentes");
        m28.setCuatrimestre((byte)8);
        m28.setNotaPromocion(notaPromocion);
        m28.addCorrelativa(m19);
        Materia m29=new Materia();
        m29.setCuatrimestre((byte)9);
        m29.setNombre("Sistemas de tiempo real");
        m29.addCorrelativa(m18);
        m29.setNotaPromocion(notaPromocion);
        Materia m30=new Materia();
        m30.setNombre("Sistemas paralelos");
        m30.setCuatrimestre((byte)9);
        m30.setNotaPromocion(notaPromocion);
        m30.addCorrelativa(m14);
        m30.addCorrelativa(m25);
        Materia m31=new Materia();
        m31.setNombre("Bases de datos distribuidas");
        m31.setCuatrimestre((byte)9);
        m31.setNotaPromocion(notaPromocion);
        m31.addCorrelativa(m21);
        m31.addCorrelativa(m22);
        Materia m32=new Materia();
        m32.setNombre("Seminario de seguridad");
        m32.setCuatrimestre((byte)9);
        m32.setNotaPromocion(notaPromocion);
        m32.addCorrelativa(m22);
        Materia m33 = new Materia();
        m33.setCuatrimestre((byte)10);
        m33.setNombre("Modelos y simulacion");
        m33.setNotaPromocion(notaPromocion);
        m33.addCorrelativa(m23);
        m33.addCorrelativa(m10);
        Materia m34 = new Materia();
        m34.setCuatrimestre((byte)10);
        m34.setNotaPromocion(notaPromocion);
        m34.setNombre("Proyecto de Software");
        m34.addCorrelativa(m26);
        Materia m35=new Materia();
        m35.setCuatrimestre((byte)10);
        m35.setNombre("Tesina");
        m35.setNotaPromocion(notaPromocion);
        m35.addCorrelativa(m22);
        m35.addCorrelativa(m23);
        m35.addCorrelativa(m24);
        m35.addCorrelativa(m25);
        m35.addCorrelativa(m26);
        m35.addCorrelativa(m27);
        m35.addCorrelativa(m28);
        planPrueba.addMateria(m1);
        planPrueba.addMateria(m2);
        planPrueba.addMateria(m3);
        planPrueba.addMateria(m4);
        planPrueba.addMateria(m5);
        planPrueba.addMateria(m6);
        planPrueba.addMateria(m7);
        planPrueba.addMateria(m8);
        planPrueba.addMateria(m9);
        planPrueba.addMateria(m10);
        planPrueba.addMateria(m11);
        planPrueba.addMateria(m12);
        planPrueba.addMateria(m13);
        planPrueba.addMateria(m14);
        planPrueba.addMateria(m15);
        planPrueba.addMateria(m16);
        planPrueba.addMateria(m17);
        planPrueba.addMateria(m18);
        planPrueba.addMateria(m19);
        planPrueba.addMateria(m20);
        planPrueba.addMateria(m21);
        planPrueba.addMateria(m22);
        planPrueba.addMateria(m23);
        planPrueba.addMateria(m24);
        planPrueba.addMateria(m25);
        planPrueba.addMateria(m26);
        planPrueba.addMateria(m27);
        planPrueba.addMateria(m28);
        planPrueba.addMateria(m29);
        planPrueba.addMateria(m30);
        planPrueba.addMateria(m31);
        planPrueba.addMateria(m32);
        planPrueba.addMateria(m33);
        planPrueba.addMateria(m34);
        planPrueba.addMateria(m35);
        planPrueba.addMateria(mo1);
        planPrueba.addMateria(mo2);
        planPrueba.addMateria(mo3);
        Carrera carreraPrueba = new Carrera();
        carreraPrueba.setNombre("Licenciatura en sistemas(Correlatividad A)");
        carreraPrueba.setPlan(planPrueba);
        listaPlanes.add(planPrueba);
        listaCarreras.add(carreraPrueba);
        Alumno a1= new Alumno();
        a1.setCarrera(carreraPrueba);
        a1.setDocumento(40001169);
        a1.setEdad((byte)27);
        a1.setNombre("Lucas");
        listaAlumnos.add(a1);


        PlanDeEstudio planPruebaB= new PlanDeEstudio();
        planPruebaB.setCantidadOptativasNecesarias((byte) 2);
        planPruebaB.setTipoCorrelatividad('B');
        planPruebaB.setNombrePlan("Plan prueba B");
        planPruebaB.addMateria(m1);
        planPruebaB.addMateria(m2);
        planPruebaB.addMateria(m3);
        planPruebaB.addMateria(m4);
        planPruebaB.addMateria(m5);
        planPruebaB.addMateria(m6);
        planPruebaB.addMateria(m7);
        planPruebaB.addMateria(m8);
        planPruebaB.addMateria(m9);
        planPruebaB.addMateria(m10);
        planPruebaB.addMateria(m11);
        planPruebaB.addMateria(m12);
        planPruebaB.addMateria(m13);
        planPruebaB.addMateria(m14);
        planPruebaB.addMateria(m15);
        planPruebaB.addMateria(m16);
        planPruebaB.addMateria(m17);
        planPruebaB.addMateria(m18);
        planPruebaB.addMateria(m19);
        planPruebaB.addMateria(m20);
        planPruebaB.addMateria(m21);
        planPruebaB.addMateria(m22);
        planPruebaB.addMateria(m23);
        planPruebaB.addMateria(m24);
        planPruebaB.addMateria(m25);
        planPruebaB.addMateria(m26);
        planPruebaB.addMateria(m27);
        planPruebaB.addMateria(m28);
        planPruebaB.addMateria(m29);
        planPruebaB.addMateria(m30);
        planPruebaB.addMateria(m31);
        planPruebaB.addMateria(m32);
        planPruebaB.addMateria(m33);
        planPruebaB.addMateria(m34);
        planPruebaB.addMateria(m35);
        planPruebaB.addMateria(mo1);
        planPruebaB.addMateria(mo2);
        planPruebaB.addMateria(mo3);
        Carrera carreraPruebaB = new Carrera();
        carreraPruebaB.setNombre("Licenciatura en sistemas(Correlatividad B)");
        carreraPruebaB.setPlan(planPruebaB);
        listaPlanes.add(planPruebaB);
        listaCarreras.add(carreraPruebaB);
        Alumno a2= new Alumno();
        a2.setCarrera(carreraPruebaB);
        a2.setDocumento(40001111);
        a2.setEdad((byte)21);
        a2.setNombre("Alumno B");
        listaAlumnos.add(a2);


        PlanDeEstudio planPruebaC= new PlanDeEstudio();
        planPruebaC.setCantidadOptativasNecesarias((byte) 2);
        planPruebaC.setTipoCorrelatividad('C');
        planPruebaC.setNombrePlan("Plan prueba C");
        planPruebaC.addMateria(m1);
        planPruebaC.addMateria(m2);
        planPruebaC.addMateria(m3);
        planPruebaC.addMateria(m4);
        planPruebaC.addMateria(m5);
        planPruebaC.addMateria(m6);
        planPruebaC.addMateria(m7);
        planPruebaC.addMateria(m8);
        planPruebaC.addMateria(m9);
        planPruebaC.addMateria(m10);
        planPruebaC.addMateria(m11);
        planPruebaC.addMateria(m12);
        planPruebaC.addMateria(m13);
        planPruebaC.addMateria(m14);
        planPruebaC.addMateria(m15);
        planPruebaC.addMateria(m16);
        planPruebaC.addMateria(m17);
        planPruebaC.addMateria(m18);
        planPruebaC.addMateria(m19);
        planPruebaC.addMateria(m20);
        planPruebaC.addMateria(m21);
        planPruebaC.addMateria(m22);
        planPruebaC.addMateria(m23);
        planPruebaC.addMateria(m24);
        planPruebaC.addMateria(m25);
        planPruebaC.addMateria(m26);
        planPruebaC.addMateria(m27);
        planPruebaC.addMateria(m28);
        planPruebaC.addMateria(m29);
        planPruebaC.addMateria(m30);
        planPruebaC.addMateria(m31);
        planPruebaC.addMateria(m32);
        planPruebaC.addMateria(m33);
        planPruebaC.addMateria(m34);
        planPruebaC.addMateria(m35);
        planPruebaC.addMateria(mo1);
        planPruebaC.addMateria(mo2);
        planPruebaC.addMateria(mo3);
        Carrera carreraPruebaC = new Carrera();
        carreraPruebaC.setNombre("Licenciatura en sistemas(Correlatividad C)");
        carreraPruebaC.setPlan(planPruebaC);
        listaPlanes.add(planPruebaC);
        listaCarreras.add(carreraPruebaC);
        Alumno a3= new Alumno();
        a3.setCarrera(carreraPruebaC);
        a3.setDocumento(40001111);
        a3.setEdad((byte)21);
        a3.setNombre("Alumno C");
        listaAlumnos.add(a3);




        PlanDeEstudio planPruebaD= new PlanDeEstudio();
        planPruebaD.setCantidadOptativasNecesarias((byte) 2);
        planPruebaD.setTipoCorrelatividad('D');
        planPruebaD.setNombrePlan("Plan prueba D");
        planPruebaD.addMateria(m1);
        planPruebaD.addMateria(m2);
        planPruebaD.addMateria(m3);
        planPruebaD.addMateria(m4);
        planPruebaD.addMateria(m5);
        planPruebaD.addMateria(m6);
        planPruebaD.addMateria(m7);
        planPruebaD.addMateria(m8);
        planPruebaD.addMateria(m9);
        planPruebaD.addMateria(m10);
        planPruebaD.addMateria(m11);
        planPruebaD.addMateria(m12);
        planPruebaD.addMateria(m13);
        planPruebaD.addMateria(m14);
        planPruebaD.addMateria(m15);
        planPruebaD.addMateria(m16);
        planPruebaD.addMateria(m17);
        planPruebaD.addMateria(m18);
        planPruebaD.addMateria(m19);
        planPruebaD.addMateria(m20);
        planPruebaD.addMateria(m21);
        planPruebaD.addMateria(m22);
        planPruebaD.addMateria(m23);
        planPruebaD.addMateria(m24);
        planPruebaD.addMateria(m25);
        planPruebaD.addMateria(m26);
        planPruebaD.addMateria(m27);
        planPruebaD.addMateria(m28);
        planPruebaD.addMateria(m29);
        planPruebaD.addMateria(m30);
        planPruebaD.addMateria(m31);
        planPruebaD.addMateria(m32);
        planPruebaD.addMateria(m33);
        planPruebaD.addMateria(m34);
        planPruebaD.addMateria(m35);
        planPruebaD.addMateria(mo1);
        planPruebaD.addMateria(mo2);
        planPruebaD.addMateria(mo3);
        Carrera carreraPruebaD = new Carrera();
        carreraPruebaD.setNombre("Licenciatura en sistemas(Correlatividad D)");
        carreraPruebaD.setPlan(planPruebaD);
        listaPlanes.add(planPruebaD);
        listaCarreras.add(carreraPruebaD);
        Alumno a4= new Alumno();
        a4.setCarrera(carreraPruebaD);
        a4.setDocumento(44444444);
        a4.setEdad((byte)24);
        a4.setNombre("Alumno D");
        listaAlumnos.add(a4);


        PlanDeEstudio planPruebaE= new PlanDeEstudio();
        planPruebaE.setCantidadOptativasNecesarias((byte) 2);
        planPruebaE.setTipoCorrelatividad('E');
        planPruebaE.setNombrePlan("Plan prueba E");
        planPruebaE.addMateria(m1);
        planPruebaE.addMateria(m2);
        planPruebaE.addMateria(m3);
        planPruebaE.addMateria(m4);
        planPruebaE.addMateria(m5);
        planPruebaE.addMateria(m6);
        planPruebaE.addMateria(m7);
        planPruebaE.addMateria(m8);
        planPruebaE.addMateria(m9);
        planPruebaE.addMateria(m10);
        planPruebaE.addMateria(m11);
        planPruebaE.addMateria(m12);
        planPruebaE.addMateria(m13);
        planPruebaE.addMateria(m14);
        planPruebaE.addMateria(m15);
        planPruebaE.addMateria(m16);
        planPruebaE.addMateria(m17);
        planPruebaE.addMateria(m18);
        planPruebaE.addMateria(m19);
        planPruebaE.addMateria(m20);
        planPruebaE.addMateria(m21);
        planPruebaE.addMateria(m22);
        planPruebaE.addMateria(m23);
        planPruebaE.addMateria(m24);
        planPruebaE.addMateria(m25);
        planPruebaE.addMateria(m26);
        planPruebaE.addMateria(m27);
        planPruebaE.addMateria(m28);
        planPruebaE.addMateria(m29);
        planPruebaE.addMateria(m30);
        planPruebaE.addMateria(m31);
        planPruebaE.addMateria(m32);
        planPruebaE.addMateria(m33);
        planPruebaE.addMateria(m34);
        planPruebaE.addMateria(m35);
        planPruebaE.addMateria(mo1);
        planPruebaE.addMateria(mo2);
        planPruebaE.addMateria(mo3);
        Carrera carreraPruebaE = new Carrera();
        carreraPruebaE.setNombre("Licenciatura en sistemas(Correlatividad E)");
        carreraPruebaE.setPlan(planPruebaE);
        listaPlanes.add(planPruebaE);
        listaCarreras.add(carreraPruebaE);
        Alumno a5= new Alumno();
        a5.setCarrera(carreraPruebaE);
        a5.setDocumento(55555555);
        a5.setEdad((byte)25);
        a5.setNombre("Alumno E");
        listaAlumnos.add(a5);
    }

}